test:
  quiet: true
  base_uri: http://test.ruslanledesma.com
  feed: http://ruslanledesma.com/feed.xml # reset by env for end-to-end test
  confirmation_uri: http://newsletter.ruslanledesma.com
  subject: 'Test <%= title %> - <%= date %>'
  from: '<%= title %> <no-reply@ruslanledesma.com>'
  html_template: test.html.erb
  plain_template: test.txt.erb
  smtp_host: localhost # reset by env for end-to-end test
  smtp_port: 25 # reset by env for end-to-end test
  smtp_user:
  smtp_pass:
  smtp_auth:
  smtp_ttls: false
